<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>storagetweaks</AssemblyName>
    <RootNamespace>Calloatti.StorageTweaks</RootNamespace>
    <TimberbornPath>C:\Program Files (x86)\Steam\steamapps\common\timberborn_main\Timberborn_Data\Managed</TimberbornPath>
  </PropertyGroup>

  <Import Project="CommonModSettings.props" />

  <ItemGroup>
    <None Update="GoodVisualization\GoodVisualization.Dirt.blueprint.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>

